### ISSUE TITLE
Add player info command

### ISSUE THREAD

**Issue by bcbwilla** [bcbwilla/FourierMC#10]
Similar to `/ncp info <playername>` in [NoCheatPlus](https://github.com/NoCheatPlus/NoCheatPlus), it would allow you to see a player's recent violations.

**Comment by ryanwarsaw** [comment]
@bcbwilla Do you plan on sticking to the existing Bukkit command framework, or transitioning to a alternative framework such as sk89q's command framework, or aphelion? I'd like to try my hand at this.

**Comment by bcbwilla** [comment]
Cool, thanks. At this point I'd lean towards the Bukkit system, but I'm open to using other frameworks if it makes things easier or better.

**Comment by bcbwilla** [comment]
Fixed in ef52390a03c63a78a0a84a7689aa73daf27d30c7
