### ISSUE TITLE
Will increment click counter when standing on a pressureplate

### ISSUE THREAD

**Issue by 058c37a272bed3464d47f0b01038a16a** [bcbwilla/FourierMC#2]
PlayerInteractEvent is also called for right clicks and for interacting with pressureplates, which is not accounted for when incrementing the click counter for the player.

**Comment by bcbwilla** [comment]
The pressure plate is an issue.  Recording right clicks is intended because autoclickers are often used to block spam, but I may consider splitting up the detection of left and right clicks so they can be analyzed separately.

**Comment by bcbwilla** [comment]
Closed by #3.  Thanks @Electroid and @RainoBoy97!
