### ISSUE TITLE
Coding conventions (diamond operator)

### ISSUE THREAD

**Issue by ryanwarsaw** [bcbwilla/FourierMC#6]
For Java 7 and up, there is the Diamond operator which is convention for initiating collections.

instead of: `public Map<UUID, Violation> violationLogger = new HashMap<UUID, Violation>();`

set your programming language to 7 (diamonds & multi-catch) and do: 
`public Map<UUID, Violation> violationLogger = new HashMap<>();`

You shouldn't notice a performance difference, just a little thing I caught while reading your code! :)

**Comment by bcbwilla** [comment]
Thanks for pointing this out!
